kind: Deployment
apiVersion: apps/v1
metadata:
  name: python-deployment
  labels:
    app: deployment
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: deployment
  template:
    metadata:
      labels:
        app: deployment
    spec:
      containers:
        - name: my-container
          image: youn8233/hellopython:1.2
          ports:
            - containerPort: 30002