apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: service
spec:
  type: NodePort
  selector:
    app: service
  ports:
    - name: http
      protocol: TCP
      nodeport: 30002 
      port: 5000         
      targetPort: 30002 