apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: service
spec:
  type: NodePort
  selector:
    app: service
  ports:
    - name: http
      protocol: TCP
      nodeport: 30002  # Port exposed on the node
      port: 5000         # Exposed port inside the cluster
      targetPort: 30002 # Port your Spring Boot app runs on