name: build and deploy python app to kubernetes kind cluster

on: 
    push:
        branches:
        - main  

jobs:
  build-deploy:    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8' 

      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

      
    - name: Start Flask app and test endpoint
      run: |
        cd src
        python main.py &
        sleep 5
        curl -f http://127.0.0.1:30002 || (echo "Flask app failed to start" && exit 1)


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/hellopython:1.2

   
    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl get nodes
        kubectl apply -f kubernetes/deployment.yaml 
        kubectl apply -f kubernetes/service.yaml 

    - name: Verify Deployment
      run: kubectl get pods